# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Lu Zhang
title: 
email: lu_zhang@g.harvard.edu
website: https://luzhangh.github.io

# Social links
#twitter_username: facespics
github_username:  LuZhangH
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: chillwildlife
linkedin_username: lu-zhang-91a7b1101
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Lu Zhang and I'm a .... 

  

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in statistics some of my other interests and hobbies are:
   - Squash
#   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
