# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Lu Zhang
title: 
email: lu_zhang@g.harvard.edu
website: https://luzhangh.github.io

# Social links
#twitter_username: facespics
github_username:  LuZhangH
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: chillwildlife
linkedin_username: lu-zhang-91a7b1101
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I am currently a PhD student in the Department of Statistics at Harvard, advised by Prof. Lucas Janson. 
  Prior to Harvard, I obtained a B.S. in Statistics from University of Science and Technology of China (USTC) in 2017.
  I am particularly interested in solving problems related to high dimensional inference, combinatorial inference, multiple testing, graphical models and reinforcement learning.
  My research finds main applications in genetics and computational neuroscience.


  

# Projects Section
projects_title: Publications & Manuscripts

# Experience Section
experience_title: Teaching & Consulting

# Education Section
educaton_title: Software

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
   Alongside my interests in Statistics some of my other interests and hobbies are:
   - Badminton
   - Squash
   - Classical Chinese poetry writing
#   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
